srun -n 4 python train.py --num-layers 4 --hidden-size 2048 --data-dir /home/sathwik7/scratch.bhatele-lab/tutorial-venv --batch-size 32 --lr 0.0001 --image-size 64 --G-intra-r 2 --G-intra-c 2 --G-data 1 --micro-batch-size 4 --checkpoint-activations
--------------------------------------------------------------------------
The library attempted to open the following supporting CUDA libraries,
but each of them failed.  CUDA-aware support is disabled.
libcuda.so.1: cannot open shared object file: No such file or directory
libcuda.dylib: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.so.1: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.dylib: cannot open shared object file: No such file or directory
If you are not interested in CUDA-aware support, then run with
--mca opal_warn_on_missing_libcuda 0 to suppress this message.  If you are interested
in CUDA-aware support, then try setting LD_LIBRARY_PATH to the location
of libcuda.so.1 to get passed this issue.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
The library attempted to open the following supporting CUDA libraries,
but each of them failed.  CUDA-aware support is disabled.
libcuda.so.1: cannot open shared object file: No such file or directory
libcuda.dylib: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.so.1: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.dylib: cannot open shared object file: No such file or directory
If you are not interested in CUDA-aware support, then run with
--mca opal_warn_on_missing_libcuda 0 to suppress this message.  If you are interested
in CUDA-aware support, then try setting LD_LIBRARY_PATH to the location
of libcuda.so.1 to get passed this issue.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
The library attempted to open the following supporting CUDA libraries,
but each of them failed.  CUDA-aware support is disabled.
libcuda.so.1: cannot open shared object file: No such file or directory
libcuda.dylib: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.so.1: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.dylib: cannot open shared object file: No such file or directory
If you are not interested in CUDA-aware support, then run with
--mca opal_warn_on_missing_libcuda 0 to suppress this message.  If you are interested
in CUDA-aware support, then try setting LD_LIBRARY_PATH to the location
of libcuda.so.1 to get passed this issue.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
The library attempted to open the following supporting CUDA libraries,
but each of them failed.  CUDA-aware support is disabled.
libcuda.so.1: cannot open shared object file: No such file or directory
libcuda.dylib: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.so.1: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.dylib: cannot open shared object file: No such file or directory
If you are not interested in CUDA-aware support, then run with
--mca opal_warn_on_missing_libcuda 0 to suppress this message.  If you are interested
in CUDA-aware support, then try setting LD_LIBRARY_PATH to the location
of libcuda.so.1 to get passed this issue.
--------------------------------------------------------------------------
Rank 0 : initialized AxoNN
Rank 0 : Model Params = 0.168009768 B
Rank 0 : Start Training with AxoNN's Intra-Layer Parallelism
Rank 0 : Epoch 0 | Iter 0/1875 | Iter Train Loss = 2.308 | Iter Time = 1.033292 s
Rank 0 : Epoch 0 | Iter 200/1875 | Iter Train Loss = 0.685 | Iter Time = 0.609139 s
Rank 0 : Epoch 0 | Iter 400/1875 | Iter Train Loss = 0.364 | Iter Time = 0.705859 s
Rank 0 : Epoch 0 | Iter 600/1875 | Iter Train Loss = 0.223 | Iter Time = 0.577115 s
Rank 0 : Epoch 0 | Iter 800/1875 | Iter Train Loss = 0.307 | Iter Time = 0.563813 s
Rank 0 : Epoch 0 | Iter 1000/1875 | Iter Train Loss = 0.245 | Iter Time = 0.612167 s
Rank 0 : Epoch 0 | Iter 1200/1875 | Iter Train Loss = 0.116 | Iter Time = 0.621056 s
Rank 0 : Epoch 0 | Iter 1400/1875 | Iter Train Loss = 0.097 | Iter Time = 0.542122 s
Rank 0 : Epoch 0 | Iter 1600/1875 | Iter Train Loss = 0.084 | Iter Time = 0.599324 s
Rank 0 : Epoch 0 | Iter 1800/1875 | Iter Train Loss = 0.130 | Iter Time = 0.555106 s
Traceback (most recent call last):
  File "train.py", line 106, in <module>
    data_json["train_acc"].append(100.*correct/total)
NameError: name 'correct' is not defined
Traceback (most recent call last):
  File "train.py", line 106, in <module>
    data_json["train_acc"].append(100.*correct/total)
NameError: name 'correct' is not defined
Traceback (most recent call last):
  File "train.py", line 106, in <module>
    data_json["train_acc"].append(100.*correct/total)
NameError: name 'correct' is not defined
Traceback (most recent call last):
  File "train.py", line 106, in <module>
    data_json["train_acc"].append(100.*correct/total)
NameError: name 'correct' is not defined
srun: error: compute-b7-42: tasks 0-3: Exited with exit code 1
